### ISSUE TITLE
Option to show in popup on demand

### ISSUE THREAD

**Issue by cheoAlejo** [qbolec/Breadcrumbs#1]
Greetings, this plugin is very very usefull.
It would be interesting to have an option to show the breadcrumbs on demand instead of all the time, also given the short length of the status bar, breadcrumbs could be shown in a popup.

Using the example from the readme, we could map the command to the F1 key to show the popup:

Given:
```
foo(){
  bar:
    if (whatever){
      cox()
    } else {
      blah->
        zoo
    }
}
```
and the carret currently in zoo, the popup could be something like:

![popup](https://user-images.githubusercontent.com/10518807/27151887-9fd793c2-5111-11e7-990d-94949ee94ab7.png)

**Comment by qbolec** [comment]
Hi! Thank you for a compliment and great suggestion!

I also feel that the space in the status bar is a limited resource, and that breadcrumbs would be more readable if presented in a separate window with colors. 

Unfortunately, the API, as I understand it, does not provide simple means to create arbitrary GUI components. A popup is definitely something one can do (as in the Color Picker plugin), but to my knowledge this requires programming everything yourself with no help from the API.

I agree that a colorful popup with syntax highlighting would be a step in the right direction! I have no idea how to do it though, right now, so I'll have to read about:
1. how to extract information from syntax highlighter for these lines
2. how to create a GUI (using the common subset of Python 2 and Python 3?)

But what, I'd really want to do, is a panel integrated with Sublime, something like these pictures: https://stackoverflow.com/questions/37013342/netbeans-style-breadcrumb-in-editor-for-intellij

**Comment by cheoAlejo** [comment]
Yes, the panel would be even better.

**Comment by cheoAlejo** [comment]
Great ! the popup works like a charm.

![2017-08-25 22_34_21-c__servidoreco_www_gd_gd_car_f_regi_car___functions php financiero - sublime](https://user-images.githubusercontent.com/10518807/29738368-6034754c-89e6-11e7-9814-25ac5a51f625.png)

Thanks for the work @qbolec @braver

**Comment by qbolec** [comment]
Nice to hear that!
